version: "3.8"
services:
  mongodb:
    image: mongo:latest
    container_name: express_tasks_mongodb
    ports:
      - "27017:27017"
    volumes:
      - "./mongodb_data:/data/db"
    restart: unless-stopped
    env_file:
      - ./.env